### ISSUE TITLE
Cannot reliably make this work :-(

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#25]
I thought I had everythign working. I shut it down, restarted it, went to services and entered my odbms key, started up the first 3 services. When I go to the 'search' pages I see nothing - no movies, no actors, nothing. Even when I go to the 'legacy' pages and run a search there then go back to the 'search' pages still nothing. 

We need to make this more fool proof! I'm clearly playing a strong fool card here 'cos I can't figure it out :-(

**Comment by TobyHFerguson** [comment]
I thought I'd got this fixed - I learnt today I needed to use an asterisk to get the search to work. But once I'd pulled everything down and rebuilt it again I found I couldn't get the search stuff to work. There's something going on here that is baffling me, unfortunately :-(

**Comment by TobyHFerguson** [comment]
I discovered taht adding `--force-recreate --build` seemed to make things reliable. Not 100% sure, but adding this note 'cos I think my last set of tests (interrupted, unfortunately) showed that. To be retried ...

**Comment by tgrall** [comment]
Redis service, based on `redislabs/redismod` does not have persistence enabled by default.

I will move the `redis-service` to a custom docker image and enable append only persistence

See issue #38

**Comment by tgrall** [comment]
@TobyHFerguson with the new redis docker image, Redis database is persisted so if you do:

`docker-compose up`

`docker-compose stop`

`docker-compose start`

you should see all your data in Redis
