### ISSUE TITLE
Autocomplete service toggle buttons don't work

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#26]
I tried toggling the Redis Search Services buttons on the Autocomplete service. In both cases, after a second or so, the button slid back to its previous position. I don't know whether this is a UI bug or something deeper

**Comment by tgrall** [comment]
I am not using this feature anymore in the demonstration.
I did build it initially when I was going in lot of detail about the implementation, and wanted to disconnect the Indexing capabilities and the suggestion one.

I will remove the configuration from the service page, but the REST API and code will still be here.

So in the `[StreamsToRediSearch](https://github.com/tgrall/redis-microservices-demo/blob/master/streams-to-redisearch-service/src/main/java/io/redis/demos/services/search/service/StreamsToRediSearch.java)` class you have 2 groups of consumers:

* `cdc.search.index`  :  to take stream data to HASHES (so not really to search ... but remember it was developed on RediSearch V1)
* `cdc.search.suggest`  : to take stream data and call FT.SUGADD

I could have use multiple services, like I did for Graph, but I thought it was interesting to show multiple groups inthe same application to open the discussion around Redis Streams consumers
