### ISSUE TITLE
'refresh' arrow in movies listing doesn't change the cursor

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#28]
When one hovers over the clockwise refresh arrow in the movies listing the cursor doesn't change to show that the item can be clicked on. I'd expect that, like most buttons or links, the cursor would change once over the arrow.

**Comment by tgrall** [comment]
I have replace the simple icon by a button to make sure that the user see that he can click. I also add a tooltip to it

![Screenshot 2020-10-22 at 10 11 31](https://user-images.githubusercontent.com/541250/96843782-ff68e080-144e-11eb-85af-a203667600ed.png)
