### ISSUE TITLE
Enhancement request: Add a count of the number of times a call is made to IMDB

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#44]
IMDB only permits 1000 requests a day - caching can help reduce that number. It would be nice to show the number of requests to IMDB and demonstrate that caching helps in that reduction. Similar to the response time number we could have another number on the Movies (Legacy) page that shows the 24 hour accumulated IMDB requests. (Unlike the response time number this number would be shared across all movies and actors)

**Comment by tgrall** [comment]
I have divided this issue in 2:

* this one to count
* the issue #50 for rate limiting (1000 req / 24h)
