### ISSUE TITLE
Auto-complete - no movie shown, just the title

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#51]
Minor issue. Just to be complete it would be good to show that when a suggested movie is selected then that movie record is pulled up - it just rounds out the whole experience. But low priority - we can just hand wave for now :-)

**Comment by tgrall** [comment]
Nothing is implemented here. The idea was simply to show the suggest.

**Comment by tgrall** [comment]
No when user selects a movie or actor it is visible in the page
