### ISSUE TITLE
suggestion seems to throw strange matches

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#52]
If I go to the auto-suggest page and type in 'ta' I see this:

![image](https://user-images.githubusercontent.com/6525189/97507925-86c8bf00-193b-11eb-97c3-929f31521062.png)

But if I type in 'tard' I get no matches. Why doesn't this match 'Bastards'?

Furthermore, if I type 'the' I can see the movie 'The Fly', but if I then immediately type in 'Fly' I see 'The Fly' come up briefly, and then go away. Typing in 'Fly' again doesn't cause this to happen. What's going on here?

**Comment by tgrall** [comment]
removed the fuzzy search to keep this feature as simple as possible
