### ISSUE TITLE
Log output to file, not to stdout

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#58]
Logging to stdout means that the workshop user's terminal is full of stuff that we don't want to talk about! What would be great is if they were simply left with the output of docker-compose and the log information went to a file or files somewhere. 

Not important, but makes the workshop look cleaner, and needs less explanation.

**Comment by tgrall** [comment]
I prefer not to do that, make it harder to debug. 

You can just start the containers in the background using: `-d`

 * `docker-compose up --build -d`
 * `docker-compose up -d`

_(I am using JUL so you can if needed)_
