### ISSUE TITLE
Total number of calls should be shown alongside latency

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#59]
Although the total number of calls is logically shared across all database entries it is much easier to observe if it is shown alongside any and all the latency numbers. Otherwise the user has to switch from one location to another, when really we just want to shown them, right there, what caching has done:

* reduced latency by a factor of 100
* reduced the use of a critical resource to virtually 0

**Comment by tgrall** [comment]
@TobyHFerguson 

![Screenshot 2020-11-05 at 09 13 44](https://user-images.githubusercontent.com/541250/98214806-41158300-1f47-11eb-9cda-30d40e7e6385.png)
